# Generated by Django 4.1.7 on 2023-04-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                (
                    "sentence",
                    models.TextField(
                        max_length=50, null=True, unique=True, verbose_name="URLコード"
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="ソート")),
            ],
            options={
                "db_table": "news",
            },
        ),
    ]
