# Generated by Django 4.1.7 on 2023-04-30 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
