# Generated by Django 4.1.7 on 2023-04-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_news_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="sentence",
            field=models.TextField(null=True, unique=True, verbose_name="内容"),
        ),
    ]
