# Generated by Django 4.1.7 on 2023-05-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_news_sentence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="タイトル"
                    ),
                ),
                ("sentence", models.TextField(verbose_name="内容")),
            ],
            options={
                "db_table": "question",
            },
        ),
    ]
