# Generated by Django 4.1.7 on 2023-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_question_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(
                choices=[
                    ("smooth", "SmoothNoteについて"),
                    ("noti", "NotiSaveについて"),
                    ("others", "その他"),
                ],
                default="smooth",
                max_length=255,
                verbose_name="質問内容",
            ),
        ),
    ]
