# Generated by Django 4.1.7 on 2023-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_question_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="sentence",
            field=models.TextField(verbose_name="詳細"),
        ),
    ]
